import type { UnitConfig } from '@/types'

export const UNITS: UnitConfig[] = [
  {
    id: 'unit1',
    label: 'Unit I',
    description: 'General English',
    headerBg: 'bg-blue-600',
    borderColor: 'border-blue-200',
    topicBtnColor: 'bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100 active:bg-blue-200',
    badgeColor: 'bg-blue-100 text-blue-700',
    topics: [
      { id: 'comprehension',        label: 'Comprehension' },
      { id: 'synonyms_antonyms',    label: 'Synonyms and Antonyms' },
      { id: 'idioms_phrases',       label: 'Idioms and Phrases' },
      { id: 'active_passive_voice', label: 'Active & Passive Voice' },
      { id: 'paragraph_writing',    label: 'Paragraph Writing — Pronouns, Homonyms' },
      { id: 'prepositions',         label: 'Uses of Prepositions' },
      { id: 'modals',               label: 'Modals' },
      { id: 'articles',             label: 'Articles' },
      { id: 'narration',            label: 'Narration (Direct & Indirect Speech)' },
      { id: 'editing',              label: 'Editing / Proof Reading' },
      { id: 'jumbled_sentences',    label: 'Rearranging of Jumbled Sentences' },
      { id: 'clauses',              label: 'Clauses' },
      { id: 'punctuation',          label: 'Punctuation' },
    ],
  },
  {
    id: 'unit2',
    label: 'Unit II',
    description: 'General Awareness (J&K Focus)',
    headerBg: 'bg-emerald-600',
    borderColor: 'border-emerald-200',
    topicBtnColor: 'bg-emerald-50 text-emerald-700 border-emerald-200 hover:bg-emerald-100 active:bg-emerald-200',
    badgeColor: 'bg-emerald-100 text-emerald-700',
    topics: [
      { id: 'culture_heritage_freedom',    label: 'Culture, Heritage & Freedom Struggle' },
      { id: 'current_events',              label: 'Current Events' },
      { id: 'political_physical_divisions',label: 'Political & Physical Divisions of India' },
      { id: 'rivers_lakes',                label: 'Important Rivers & Lakes' },
      { id: 'jk_history',                  label: 'J&K — History & Politics' },
      { id: 'weather_climate_crops',       label: 'Weather, Climate, Crops & Transport' },
      { id: 'demography_census',           label: 'Demography — Census' },
      { id: 'jk_tourist_destinations',     label: 'J&K — Tourist Destinations' },
      { id: 'jk_economy',                  label: 'J&K — Economy' },
    ],
  },
  {
    id: 'unit3',
    label: 'Unit III',
    description: 'Numerical & Reasoning Ability',
    headerBg: 'bg-orange-500',
    borderColor: 'border-orange-200',
    topicBtnColor: 'bg-orange-50 text-orange-700 border-orange-200 hover:bg-orange-100 active:bg-orange-200',
    badgeColor: 'bg-orange-100 text-orange-700',
    topics: [
      { id: 'coding_decoding',      label: 'Coding-Decoding' },
      { id: 'number_series',        label: 'Number Series' },
      { id: 'number_system',        label: 'Number System' },
      { id: 'ratio_proportion',     label: 'Ratio & Proportion' },
      { id: 'speed_distance_time',  label: 'Speed, Distance and Time' },
      { id: 'average',              label: 'Average' },
      { id: 'mathematical_reasoning', label: 'Mathematical Reasoning' },
      { id: 'time_work',            label: 'Time & Work' },
      { id: 'percentage',           label: 'Percentage' },
      { id: 'direction_sense',      label: 'Direction Sense' },
      { id: 'blood_relations',      label: 'Blood Relations' },
      { id: 'statements_conclusions', label: 'Statements & Conclusions' },
      { id: 'profit_loss',          label: 'Profit & Loss' },
      { id: 'letter_series',        label: 'Letter Series' },
    ],
  },
  {
    id: 'unit4',
    label: 'Unit IV',
    description: 'Basic Concepts of Computers',
    headerBg: 'bg-violet-600',
    borderColor: 'border-violet-200',
    topicBtnColor: 'bg-violet-50 text-violet-700 border-violet-200 hover:bg-violet-100 active:bg-violet-200',
    badgeColor: 'bg-violet-100 text-violet-700',
    topics: [
      { id: 'fundamentals',         label: 'Fundamentals of Computer Sciences' },
      { id: 'email_internet',       label: 'Email & Internet' },
      { id: 'hardware_software',    label: 'Hardware & Software' },
      { id: 'ms_office',            label: 'MS Word, Excel, Access & PowerPoint' },
      { id: 'operating_system',     label: 'Operating System' },
      { id: 'input_output_devices', label: 'Input & Output Devices' },
    ],
  },
]
